#!/bin/bash
if [[ $1 = 61 ]]; then
  echo using scotch 6.1.1
  export PREF=/home/fux/configs/scotch6.1.1;
elif [[ $1 = 62 ]]; then
  echo using scotch 6.1.2
  export PREF=/home/fux/configs/skotx_6.1.2/
elif [[ $1 = 7 ]]; then
  echo using scotch 7.0.1
  export PREF=/home/fux/configs/scotch7.0.1
else
  echo no scotch version
fi
mpif90 -g -o debug_$1 -I$PREF/include -DSCOTCH_INTSIZE=8 debug_new.F90 -L$PREF/lib -lptscotch -lscotch -lscotcherrexit
