file(GLOB files1 "*")
foreach(f1 ${files1})
  if(IS_DIRECTORY ${f1})
    message(STATUS "niveau 1 => ${f1}")
    file(GLOB files2 "${f1}/*")
    foreach(f2 ${files2})
      if(IS_DIRECTORY ${f2})
         message(STATUS "niveau 2 => ${f2}")
      endif()
    endforeach(f2 ${files2})
  endif(IS_DIRECTORY ${f1})
endforeach(f1 ${files1})
